name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: iterative/setup-cml@v2

      - name: Install Packages
        run: make install

      - name: Format
        run: make format

      - name: Train
        run: make train

      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      - name: Upload model and results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-results
          path: |
            Results/model_results.png
            Results/metrics.txt
            Model/drug_pipeline.skops

      - name: Update Branch
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
